/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__line_token1 = 1,
  anon_sym_LF = 2,
  aux_sym_raw_text_token1 = 3,
  anon_sym_POUND = 4,
  anon_sym_PERCENT = 5,
  anon_sym_x = 6,
  anon_sym_DASH = 7,
  anon_sym_QMARK = 8,
  anon_sym_TILDE = 9,
  anon_sym_BANG = 10,
  anon_sym_BANG_BANG = 11,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 12,
  sym_source_file = 13,
  sym__line = 14,
  sym_raw_text = 15,
  sym_comment = 16,
  sym_section = 17,
  sym_done = 18,
  sym_todo = 19,
  sym_question = 20,
  sym_partial = 21,
  sym_important = 22,
  sym_urgent = 23,
  sym_plain = 24,
  sym_code_block = 25,
  sym_code_fence_start = 26,
  sym_code_language = 27,
  sym_code_fence_end = 28,
  sym_code_line = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_code_block_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__line_token1] = "_line_token1",
  [anon_sym_LF] = "\n",
  [aux_sym_raw_text_token1] = "raw_text_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_PERCENT] = "% ",
  [anon_sym_x] = "x ",
  [anon_sym_DASH] = "- ",
  [anon_sym_QMARK] = "\? ",
  [anon_sym_TILDE] = "~ ",
  [anon_sym_BANG] = "! ",
  [anon_sym_BANG_BANG] = "!! ",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_section] = "section",
  [sym_done] = "done",
  [sym_todo] = "todo",
  [sym_question] = "question",
  [sym_partial] = "partial",
  [sym_important] = "important",
  [sym_urgent] = "urgent",
  [sym_plain] = "plain",
  [sym_code_block] = "code_block",
  [sym_code_fence_start] = "code_fence_start",
  [sym_code_language] = "code_language",
  [sym_code_fence_end] = "code_fence_end",
  [sym_code_line] = "code_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_code_block_repeat1] = "code_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_raw_text_token1] = aux_sym_raw_text_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_BANG_BANG] = anon_sym_BANG_BANG,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_section] = sym_section,
  [sym_done] = sym_done,
  [sym_todo] = sym_todo,
  [sym_question] = sym_question,
  [sym_partial] = sym_partial,
  [sym_important] = sym_important,
  [sym_urgent] = sym_urgent,
  [sym_plain] = sym_plain,
  [sym_code_block] = sym_code_block,
  [sym_code_fence_start] = sym_code_fence_start,
  [sym_code_language] = sym_code_language,
  [sym_code_fence_end] = sym_code_fence_end,
  [sym_code_line] = sym_code_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_code_block_repeat1] = aux_sym_code_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_raw_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_done] = {
    .visible = true,
    .named = true,
  },
  [sym_todo] = {
    .visible = true,
    .named = true,
  },
  [sym_question] = {
    .visible = true,
    .named = true,
  },
  [sym_partial] = {
    .visible = true,
    .named = true,
  },
  [sym_important] = {
    .visible = true,
    .named = true,
  },
  [sym_urgent] = {
    .visible = true,
    .named = true,
  },
  [sym_plain] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_fence_start] = {
    .visible = true,
    .named = true,
  },
  [sym_code_language] = {
    .visible = true,
    .named = true,
  },
  [sym_code_fence_end] = {
    .visible = true,
    .named = true,
  },
  [sym_code_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '?') ADVANCE(19);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead == 'x') ADVANCE(20);
      if (lookahead == '~') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '?') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(20);
      if (lookahead == '~') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '`') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '`') ADVANCE(5);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (eof) ADVANCE(7);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == '\n') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(35);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      ADVANCE_MAP(
        '!', 16,
        '#', 29,
        '%', 17,
        '-', 18,
        '?', 19,
        '`', 27,
        'x', 20,
        '~', 21,
      );
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == '!') ADVANCE(16);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '%') ADVANCE(17);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '?') ADVANCE(19);
      if (lookahead == 'x') ADVANCE(20);
      if (lookahead == '~') ADVANCE(21);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == '`') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead == '`') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_raw_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANG_BANG);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_raw_text_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_BANG_BANG] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym__line] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_code_fence_start] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__line_token1] = ACTIONS(5),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_raw_text] = STATE(32),
    [sym_comment] = STATE(44),
    [sym_section] = STATE(44),
    [sym_done] = STATE(44),
    [sym_todo] = STATE(44),
    [sym_question] = STATE(44),
    [sym_partial] = STATE(44),
    [sym_important] = STATE(44),
    [sym_urgent] = STATE(44),
    [sym_plain] = STATE(44),
    [aux_sym_raw_text_token1] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_PERCENT] = ACTIONS(13),
    [anon_sym_x] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(19),
    [anon_sym_TILDE] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(23),
    [anon_sym_BANG_BANG] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      aux_sym__line_token1,
    ACTIONS(7), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_code_fence_start,
    STATE(4), 3,
      sym__line,
      sym_code_block,
      aux_sym_source_file_repeat1,
  [18] = 5,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      aux_sym__line_token1,
    ACTIONS(34), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(25), 1,
      sym_code_fence_start,
    STATE(4), 3,
      sym__line,
      sym_code_block,
      aux_sym_source_file_repeat1,
  [36] = 5,
    ACTIONS(37), 1,
      aux_sym_raw_text_token1,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(11), 1,
      aux_sym_code_block_repeat1,
    STATE(12), 1,
      sym_code_fence_end,
    STATE(29), 1,
      sym_code_line,
  [52] = 5,
    ACTIONS(37), 1,
      aux_sym_raw_text_token1,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(5), 1,
      aux_sym_code_block_repeat1,
    STATE(9), 1,
      sym_code_fence_end,
    STATE(29), 1,
      sym_code_line,
  [68] = 5,
    ACTIONS(37), 1,
      aux_sym_raw_text_token1,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(8), 1,
      aux_sym_code_block_repeat1,
    STATE(12), 1,
      sym_code_fence_end,
    STATE(29), 1,
      sym_code_line,
  [84] = 5,
    ACTIONS(37), 1,
      aux_sym_raw_text_token1,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(11), 1,
      aux_sym_code_block_repeat1,
    STATE(13), 1,
      sym_code_fence_end,
    STATE(29), 1,
      sym_code_line,
  [100] = 3,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_LF,
    ACTIONS(43), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [111] = 2,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 3,
      aux_sym__line_token1,
      anon_sym_LF,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [120] = 4,
    ACTIONS(51), 1,
      aux_sym_raw_text_token1,
    ACTIONS(54), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(11), 1,
      aux_sym_code_block_repeat1,
    STATE(29), 1,
      sym_code_line,
  [133] = 3,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 1,
      anon_sym_LF,
    ACTIONS(58), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [144] = 3,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_LF,
    ACTIONS(64), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [155] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [163] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(72), 1,
      anon_sym_LF,
    STATE(36), 1,
      sym_raw_text,
  [173] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(74), 1,
      anon_sym_LF,
    STATE(37), 1,
      sym_raw_text,
  [183] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(76), 1,
      anon_sym_LF,
    STATE(38), 1,
      sym_raw_text,
  [193] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(78), 1,
      anon_sym_LF,
    STATE(39), 1,
      sym_raw_text,
  [203] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(80), 1,
      anon_sym_LF,
    STATE(40), 1,
      sym_raw_text,
  [213] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(82), 1,
      anon_sym_LF,
    STATE(41), 1,
      sym_raw_text,
  [223] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(84), 1,
      anon_sym_LF,
    STATE(42), 1,
      sym_raw_text,
  [233] = 3,
    ACTIONS(9), 1,
      aux_sym_raw_text_token1,
    ACTIONS(86), 1,
      anon_sym_LF,
    STATE(43), 1,
      sym_raw_text,
  [243] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [251] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [259] = 3,
    ACTIONS(92), 1,
      anon_sym_LF,
    ACTIONS(94), 1,
      aux_sym_raw_text_token1,
    STATE(34), 1,
      sym_code_language,
  [269] = 2,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 2,
      aux_sym__line_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [277] = 1,
    ACTIONS(96), 2,
      anon_sym_LF,
      aux_sym_raw_text_token1,
  [282] = 1,
    ACTIONS(54), 2,
      aux_sym_raw_text_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [287] = 1,
    ACTIONS(98), 1,
      anon_sym_LF,
  [291] = 1,
    ACTIONS(100), 1,
      anon_sym_LF,
  [295] = 1,
    ACTIONS(102), 1,
      anon_sym_LF,
  [299] = 1,
    ACTIONS(104), 1,
      anon_sym_LF,
  [303] = 1,
    ACTIONS(106), 1,
      anon_sym_LF,
  [307] = 1,
    ACTIONS(108), 1,
      anon_sym_LF,
  [311] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [315] = 1,
    ACTIONS(112), 1,
      anon_sym_LF,
  [319] = 1,
    ACTIONS(114), 1,
      anon_sym_LF,
  [323] = 1,
    ACTIONS(116), 1,
      anon_sym_LF,
  [327] = 1,
    ACTIONS(118), 1,
      anon_sym_LF,
  [331] = 1,
    ACTIONS(120), 1,
      anon_sym_LF,
  [335] = 1,
    ACTIONS(122), 1,
      anon_sym_LF,
  [339] = 1,
    ACTIONS(124), 1,
      anon_sym_LF,
  [343] = 1,
    ACTIONS(126), 1,
      anon_sym_LF,
  [347] = 1,
    ACTIONS(128), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 18,
  [SMALL_STATE(5)] = 36,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 68,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 120,
  [SMALL_STATE(12)] = 133,
  [SMALL_STATE(13)] = 144,
  [SMALL_STATE(14)] = 155,
  [SMALL_STATE(15)] = 163,
  [SMALL_STATE(16)] = 173,
  [SMALL_STATE(17)] = 183,
  [SMALL_STATE(18)] = 193,
  [SMALL_STATE(19)] = 203,
  [SMALL_STATE(20)] = 213,
  [SMALL_STATE(21)] = 223,
  [SMALL_STATE(22)] = 233,
  [SMALL_STATE(23)] = 243,
  [SMALL_STATE(24)] = 251,
  [SMALL_STATE(25)] = 259,
  [SMALL_STATE(26)] = 269,
  [SMALL_STATE(27)] = 277,
  [SMALL_STATE(28)] = 282,
  [SMALL_STATE(29)] = 287,
  [SMALL_STATE(30)] = 291,
  [SMALL_STATE(31)] = 295,
  [SMALL_STATE(32)] = 299,
  [SMALL_STATE(33)] = 303,
  [SMALL_STATE(34)] = 307,
  [SMALL_STATE(35)] = 311,
  [SMALL_STATE(36)] = 315,
  [SMALL_STATE(37)] = 319,
  [SMALL_STATE(38)] = 323,
  [SMALL_STATE(39)] = 327,
  [SMALL_STATE(40)] = 331,
  [SMALL_STATE(41)] = 335,
  [SMALL_STATE(42)] = 339,
  [SMALL_STATE(43)] = 343,
  [SMALL_STATE(44)] = 347,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_fence_end, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_fence_end, 1, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 6, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 6, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_done, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_todo, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_question, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_important, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_urgent, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_fence_start, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_text, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_line, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_language, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [110] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_done, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_todo, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_question, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_important, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urgent, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "note",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
