/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 5
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_section = 2,
  sym_done = 3,
  sym_todo = 4,
  sym_question = 5,
  sym_partial = 6,
  sym_important = 7,
  sym_urgent = 8,
  sym_plain = 9,
  sym_source_file = 10,
  sym__line = 11,
  aux_sym_source_file_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_section] = "section",
  [sym_done] = "done",
  [sym_todo] = "todo",
  [sym_question] = "question",
  [sym_partial] = "partial",
  [sym_important] = "important",
  [sym_urgent] = "urgent",
  [sym_plain] = "plain",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_section] = sym_section,
  [sym_done] = sym_done,
  [sym_todo] = sym_todo,
  [sym_question] = sym_question,
  [sym_partial] = sym_partial,
  [sym_important] = sym_important,
  [sym_urgent] = sym_urgent,
  [sym_plain] = sym_plain,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_done] = {
    .visible = true,
    .named = true,
  },
  [sym_todo] = {
    .visible = true,
    .named = true,
  },
  [sym_question] = {
    .visible = true,
    .named = true,
  },
  [sym_partial] = {
    .visible = true,
    .named = true,
  },
  [sym_important] = {
    .visible = true,
    .named = true,
  },
  [sym_urgent] = {
    .visible = true,
    .named = true,
  },
  [sym_plain] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '!') ADVANCE(1);
      if (lookahead == '#') ADVANCE(9);
      if (lookahead == '%') ADVANCE(2);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '?') ADVANCE(4);
      if (lookahead == 'x') ADVANCE(5);
      if (lookahead == '~') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(10);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '\n', 28,
        '!', 1,
        '#', 9,
        '%', 2,
        '-', 3,
        '?', 4,
        'x', 5,
        '~', 6,
        '\t', 10,
        ' ', 10,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(10);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_section);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_done);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_todo);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_question);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_partial);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_important);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_urgent);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_plain);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_plain);
      ADVANCE_MAP(
        '!', 1,
        '#', 9,
        '%', 2,
        '-', 3,
        '?', 4,
        'x', 5,
        '~', 6,
        '\t', 10,
        ' ', 10,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_section] = ACTIONS(1),
    [sym_done] = ACTIONS(1),
    [sym_todo] = ACTIONS(1),
    [sym_question] = ACTIONS(1),
    [sym_partial] = ACTIONS(1),
    [sym_important] = ACTIONS(1),
    [sym_urgent] = ACTIONS(1),
    [sym_plain] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(4),
    [sym__line] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_section] = ACTIONS(5),
    [sym_done] = ACTIONS(5),
    [sym_todo] = ACTIONS(5),
    [sym_question] = ACTIONS(5),
    [sym_partial] = ACTIONS(5),
    [sym_important] = ACTIONS(5),
    [sym_urgent] = ACTIONS(5),
    [sym_plain] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
    [sym_section] = ACTIONS(9),
    [sym_done] = ACTIONS(9),
    [sym_todo] = ACTIONS(9),
    [sym_question] = ACTIONS(9),
    [sym_partial] = ACTIONS(9),
    [sym_important] = ACTIONS(9),
    [sym_urgent] = ACTIONS(9),
    [sym_plain] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym_section] = ACTIONS(13),
    [sym_done] = ACTIONS(13),
    [sym_todo] = ACTIONS(13),
    [sym_question] = ACTIONS(13),
    [sym_partial] = ACTIONS(13),
    [sym_important] = ACTIONS(13),
    [sym_urgent] = ACTIONS(13),
    [sym_plain] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(16), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [16] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_note(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "note",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
